// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekqrhfqbnngmweflfsoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcXJoZnFibm5nbXdlZmxmc295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjQwMDQsImV4cCI6MjA2NDYwMDAwNH0.jJk4HhLfppZdn0Kph7I6SkT5dGQx3nl9JLHNoDM7vys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);